packages:
  - "packages/*"

allowBuilds:
  '@deepseek-ai/dsh-subprocess-local': true
  '@google/genai': false
  esbuild: true
  koffi: true
  msgpackr-extract: false
  node-pty: true
  protobufjs: false
blockExoticSubdeps: true
minimumReleaseAge: 0
strictDepBuilds: true
trustLockfile: false
