import { describe, expect, it } from "vitest";
import * as core from "../src/index.js";

describe("@acpus/core public API", () => {
  it("exports the current authoring, schema, expression, compiler, and runtime surface", () => {
    expect(Object.keys(core).sort()).toEqual([
      "all",
      "and",
      "any",
      "assertBoundarySchema",
      "coalesce",
      "compileWorkflowDefinition",
      "compileWorkflowModule",
      "createDollar",
      "defineWorkflow",
      "endsWith",
      "eq",
      "expr",
      "exprOps",
      "fallback",
      "gt",
      "gte",
      "head",
      "includes",
      "isEmpty",
      "isExpr",
      "len",
      "literal",
      "lt",
      "lte",
      "matches",
      "max",
      "min",
      "ne",
      "not",
      "nth",
      "or",
      "parseSchema",
      "pick",
      "refExpr",
      "runtime",
      "s",
      "safeParseSchema",
      "schemaToJsonSchema",
      "secret",
      "startsWith",
      "task",
      "template",
      "toJSONSchema",
      "toSchemaIR",
      "validateWorkflowIR",
      "valueToExprIR",
      "where",
      "z",
    ]);
  });
});
