use crate::{
    AgentAttemptTelemetry, AgentAttemptTelemetryState, AgentContextUsage, AgentIoPreview,
    AgentTelemetry, AgentTokenUsage, AgentToolCallTelemetry, AgentToolsTelemetry, ApiErrorBody,
    ApiErrorCode, ForkPlan, ForkRequest, LoopDynamicContext, NodeDynamicContext,
    NodeExecutionState, NodeKeyDynamic, NodeState, ReplayMismatch, ReplayMismatchKind,
    ReplayRequest, ReplayResult, RetryRequest, RunCleanItem, RunCleanResult, RunEvent, RunLineage,
    RunState, RunStatus, RunSummary, SignalRequest, SupervisorHealth,
};
use acpus_ir::{
    AcpusIr, AgentPolicy, AgentSpec, AgentType, IrBranch, IrExpression, IrNode, IrNodeKind,
    IrSource, NodeKeyTemplate, OutputMerge,
};
use ts_rs::{Config, TS};

pub fn typescript_bindings() -> String {
    let cfg = Config::default();
    let mut declarations = vec![
        "// @generated by acpus-runtime-api. Do not edit by hand.".to_string(),
        "export type JsonObject = Record<string, unknown>;".to_string(),
        "export type Timestamp = string;".to_string(),
        "export type RunId = string;".to_string(),
        "export type NodeKey = string;".to_string(),
        "export type NodeId = string;".to_string(),
        "export type ArtifactRef = string;".to_string(),
        "export type JsonValue = unknown;".to_string(),
        "export type NodeKeyDynamicFrame = NodeKeyDynamic;".to_string(),
        "export type AgentOverrides = JsonObject;".to_string(),
        "export type AgentOverrideWarning = JsonObject;".to_string(),
    ];

    push_decl::<AgentType>(&mut declarations, &cfg);
    push_decl::<AgentPolicy>(&mut declarations, &cfg);
    push_decl::<AgentSpec>(&mut declarations, &cfg);
    push_decl::<IrSource>(&mut declarations, &cfg);
    push_decl::<IrNodeKind>(&mut declarations, &cfg);
    push_decl::<OutputMerge>(&mut declarations, &cfg);
    push_decl::<NodeKeyTemplate>(&mut declarations, &cfg);
    push_decl::<IrExpression>(&mut declarations, &cfg);
    push_decl::<IrBranch>(&mut declarations, &cfg);
    push_decl::<IrNode>(&mut declarations, &cfg);
    push_decl::<AcpusIr>(&mut declarations, &cfg);
    push_decl::<NodeState>(&mut declarations, &cfg);
    push_decl::<RunStatus>(&mut declarations, &cfg);
    push_decl::<NodeKeyDynamic>(&mut declarations, &cfg);
    push_decl::<LoopDynamicContext>(&mut declarations, &cfg);
    push_decl::<NodeDynamicContext>(&mut declarations, &cfg);
    push_decl::<AgentContextUsage>(&mut declarations, &cfg);
    push_decl::<AgentTokenUsage>(&mut declarations, &cfg);
    push_decl::<AgentIoPreview>(&mut declarations, &cfg);
    push_decl::<AgentToolCallTelemetry>(&mut declarations, &cfg);
    push_decl::<AgentToolsTelemetry>(&mut declarations, &cfg);
    push_decl::<AgentAttemptTelemetryState>(&mut declarations, &cfg);
    push_decl::<AgentAttemptTelemetry>(&mut declarations, &cfg);
    push_decl::<AgentTelemetry>(&mut declarations, &cfg);
    push_decl::<NodeExecutionState>(&mut declarations, &cfg);
    push_decl::<RunLineage>(&mut declarations, &cfg);
    push_decl::<RunState>(&mut declarations, &cfg);
    push_decl::<RunSummary>(&mut declarations, &cfg);
    push_decl::<SupervisorHealth>(&mut declarations, &cfg);
    push_decl::<SignalRequest>(&mut declarations, &cfg);
    push_decl::<RetryRequest>(&mut declarations, &cfg);
    push_decl::<ReplayRequest>(&mut declarations, &cfg);
    push_decl::<ForkRequest>(&mut declarations, &cfg);
    push_decl::<ForkPlan>(&mut declarations, &cfg);
    push_decl::<ReplayMismatchKind>(&mut declarations, &cfg);
    push_decl::<ReplayMismatch>(&mut declarations, &cfg);
    push_decl::<ReplayResult>(&mut declarations, &cfg);
    push_decl::<RunCleanItem>(&mut declarations, &cfg);
    push_decl::<RunCleanResult>(&mut declarations, &cfg);
    push_decl::<ApiErrorCode>(&mut declarations, &cfg);
    push_decl::<ApiErrorBody>(&mut declarations, &cfg);
    push_decl::<RunEvent>(&mut declarations, &cfg);

    let bindings = declarations.join("\n\n");
    let bindings = bindings.replace(" | null", "").replace("null | ", "");
    format!("{bindings}\n")
}

fn push_decl<T: TS>(declarations: &mut Vec<String>, cfg: &Config) {
    let decl = T::decl(cfg);
    declarations.push(
        decl.strip_prefix("type ")
            .map(|tail| format!("export type {tail}"))
            .unwrap_or(decl),
    );
}
