/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import { z } from 'zod'

const ActivityNodeRemoteCodec$schema = z.object({
  'activityId': z.string(),
  'label': z.string(),
  'kind': z.string(),
  'status': z.union([z.literal("pending"), z.literal("running"), z.literal("awaiting"), z.literal("completed"), z.literal("failed"), z.literal("not_started"), z.literal("not_selected"), z.literal("starting"), z.literal("ready"), z.literal("timed_out"), z.literal("cancelled"), z.literal("mixed")]),
  'startedAt': z.string().optional(),
  'durationMs': z.number().optional(),
  'progress': z.object({
  'completed': z.number(),
  'total': z.number(),
}).optional(),
  'agent': z.object({
  'name': z.string().optional(),
  'phase': z.union([z.literal("starting"), z.literal("responding"), z.literal("reported-thought"), z.literal("planning"), z.literal("tool"), z.literal("output-repair"), z.literal("settling"), z.literal("settled")]).optional(),
  'turn': z.number().optional(),
  'tool': z.object({
  'name': z.string(),
  'title': z.string().optional(),
  'state': z.union([z.literal("running"), z.literal("completed"), z.literal("failed"), z.literal("canceled")]),
}).optional(),
  'telemetry': z.object({
  'inputTokens': z.number().optional(),
  'outputTokens': z.number().optional(),
  'totalTokens': z.number().optional(),
  'contextWindow': z.object({
  'used': z.number(),
  'size': z.number(),
}).optional(),
}).optional(),
}).optional(),
  'children': z.array(z.lazy(() => ActivityNodeRemoteCodec$schema)),
})
const ActivityNodeRemoteCodec$schema2 = z.object({
  'activityId': z.string(),
  'label': z.string(),
  'kind': z.string(),
  'status': z.union([z.literal("pending"), z.literal("running"), z.literal("awaiting"), z.literal("completed"), z.literal("failed"), z.literal("not_started"), z.literal("not_selected"), z.literal("starting"), z.literal("ready"), z.literal("timed_out"), z.literal("cancelled"), z.literal("mixed")]),
  'startedAt': z.string().optional(),
  'durationMs': z.number().optional(),
  'progress': z.object({
  'completed': z.number(),
  'total': z.number(),
}).optional(),
  'agent': z.object({
  'name': z.string().optional(),
  'phase': z.union([z.literal("starting"), z.literal("responding"), z.literal("reported-thought"), z.literal("planning"), z.literal("tool"), z.literal("output-repair"), z.literal("settling"), z.literal("settled")]).optional(),
  'turn': z.number().optional(),
  'tool': z.object({
  'name': z.string(),
  'title': z.string().optional(),
  'state': z.union([z.literal("running"), z.literal("completed"), z.literal("failed"), z.literal("canceled")]),
}).optional(),
  'telemetry': z.object({
  'inputTokens': z.number().optional(),
  'outputTokens': z.number().optional(),
  'totalTokens': z.number().optional(),
  'contextWindow': z.object({
  'used': z.number(),
  'size': z.number(),
}).optional(),
}).optional(),
}).optional(),
  'children': z.array(z.lazy(() => ActivityNodeRemoteCodec$schema2)),
})
const _acpus_dsh_acpus_awaitSessionActivityRevision_parameter_0$schema = z.object({
  'sessionId': z.string(),
  'afterRevision': z.number(),
})
const _acpus_dsh_acpus_awaitSessionActivityRevision_result$schema = z.object({
  'revision': z.number(),
})
const _acpus_dsh_acpus_cancelSessionTask_parameter_0$schema = z.object({
  'sessionId': z.string(),
  'generation': z.number(),
})
const _acpus_dsh_acpus_cancelSessionTask_result$schema = z.union([z.object({
  'status': z.literal("applied"),
  'projection': z.object({
  'sessionId': z.string(),
  'revision': z.number(),
  'tasks': z.array(z.object({
  'task': z.object({
  'name': z.string(),
  'occurrence': z.number(),
}),
  'status': z.union([z.literal("pending"), z.literal("running"), z.literal("awaiting"), z.literal("paused"), z.literal("completed"), z.literal("failed"), z.literal("canceled")]),
  'availability': z.union([z.object({
  'status': z.literal("available"),
}), z.object({
  'status': z.literal("unavailable"),
  'reason': z.union([z.literal("workspace-unavailable"), z.literal("runtime-authority-busy"), z.literal("runtime-store-unavailable"), z.literal("runtime-store-unsupported"), z.literal("runtime-configuration-invalid"), z.literal("runtime-open-failed")]),
  'workspace': z.string(),
  'detail': z.string(),
  'detectedAt': z.string(),
})]),
  'counts': z.object({
  'total': z.number(),
  'notStarted': z.number(),
  'pending': z.number(),
  'running': z.number(),
  'awaiting': z.number(),
  'completed': z.number(),
  'failed': z.number(),
  'timedOut': z.number(),
  'canceled': z.number(),
}),
  'startedAt': z.string(),
  'finishedAt': z.string().optional(),
  'forkedFrom': z.object({
  'name': z.string(),
  'occurrence': z.number(),
}).optional(),
})),
  'tasksTruncated': z.boolean(),
  'task': z.object({
  'selector': z.object({
  'name': z.string(),
  'occurrence': z.number(),
}),
  'generation': z.number(),
  'status': z.union([z.literal("pending"), z.literal("running"), z.literal("awaiting"), z.literal("paused"), z.literal("completed"), z.literal("failed"), z.literal("canceled")]),
  'availability': z.union([z.object({
  'status': z.literal("available"),
}), z.object({
  'status': z.literal("unavailable"),
  'reason': z.union([z.literal("workspace-unavailable"), z.literal("runtime-authority-busy"), z.literal("runtime-store-unavailable"), z.literal("runtime-store-unsupported"), z.literal("runtime-configuration-invalid"), z.literal("runtime-open-failed")]),
  'workspace': z.string(),
  'detail': z.string(),
  'detectedAt': z.string(),
})]),
  'counts': z.object({
  'total': z.number(),
  'notStarted': z.number(),
  'pending': z.number(),
  'running': z.number(),
  'awaiting': z.number(),
  'completed': z.number(),
  'failed': z.number(),
  'timedOut': z.number(),
  'canceled': z.number(),
}),
  'startedAt': z.string(),
  'finishedAt': z.string().optional(),
  'tree': z.array(z.object({
  'activityId': z.string(),
  'label': z.string(),
  'kind': z.string(),
  'status': z.union([z.literal("pending"), z.literal("running"), z.literal("awaiting"), z.literal("completed"), z.literal("failed"), z.literal("not_started"), z.literal("not_selected"), z.literal("starting"), z.literal("ready"), z.literal("timed_out"), z.literal("cancelled"), z.literal("mixed")]),
  'startedAt': z.string().optional(),
  'durationMs': z.number().optional(),
  'progress': z.object({
  'completed': z.number(),
  'total': z.number(),
}).optional(),
  'agent': z.object({
  'name': z.string().optional(),
  'phase': z.union([z.literal("starting"), z.literal("responding"), z.literal("reported-thought"), z.literal("planning"), z.literal("tool"), z.literal("output-repair"), z.literal("settling"), z.literal("settled")]).optional(),
  'turn': z.number().optional(),
  'tool': z.object({
  'name': z.string(),
  'title': z.string().optional(),
  'state': z.union([z.literal("running"), z.literal("completed"), z.literal("failed"), z.literal("canceled")]),
}).optional(),
  'telemetry': z.object({
  'inputTokens': z.number().optional(),
  'outputTokens': z.number().optional(),
  'totalTokens': z.number().optional(),
  'contextWindow': z.object({
  'used': z.number(),
  'size': z.number(),
}).optional(),
}).optional(),
}).optional(),
  'children': z.array(z.lazy(() => ActivityNodeRemoteCodec$schema2)),
})),
}).optional(),
}),
}), z.object({
  'status': z.literal("rejected"),
  'reason': z.union([z.literal("task-unavailable"), z.literal("temporarily-unavailable"), z.literal("already-terminal"), z.literal("not-controllable")]),
  'projection': z.object({
  'sessionId': z.string(),
  'revision': z.number(),
  'tasks': z.array(z.object({
  'task': z.object({
  'name': z.string(),
  'occurrence': z.number(),
}),
  'status': z.union([z.literal("pending"), z.literal("running"), z.literal("awaiting"), z.literal("paused"), z.literal("completed"), z.literal("failed"), z.literal("canceled")]),
  'availability': z.union([z.object({
  'status': z.literal("available"),
}), z.object({
  'status': z.literal("unavailable"),
  'reason': z.union([z.literal("workspace-unavailable"), z.literal("runtime-authority-busy"), z.literal("runtime-store-unavailable"), z.literal("runtime-store-unsupported"), z.literal("runtime-configuration-invalid"), z.literal("runtime-open-failed")]),
  'workspace': z.string(),
  'detail': z.string(),
  'detectedAt': z.string(),
})]),
  'counts': z.object({
  'total': z.number(),
  'notStarted': z.number(),
  'pending': z.number(),
  'running': z.number(),
  'awaiting': z.number(),
  'completed': z.number(),
  'failed': z.number(),
  'timedOut': z.number(),
  'canceled': z.number(),
}),
  'startedAt': z.string(),
  'finishedAt': z.string().optional(),
  'forkedFrom': z.object({
  'name': z.string(),
  'occurrence': z.number(),
}).optional(),
})),
  'tasksTruncated': z.boolean(),
  'task': z.object({
  'selector': z.object({
  'name': z.string(),
  'occurrence': z.number(),
}),
  'generation': z.number(),
  'status': z.union([z.literal("pending"), z.literal("running"), z.literal("awaiting"), z.literal("paused"), z.literal("completed"), z.literal("failed"), z.literal("canceled")]),
  'availability': z.union([z.object({
  'status': z.literal("available"),
}), z.object({
  'status': z.literal("unavailable"),
  'reason': z.union([z.literal("workspace-unavailable"), z.literal("runtime-authority-busy"), z.literal("runtime-store-unavailable"), z.literal("runtime-store-unsupported"), z.literal("runtime-configuration-invalid"), z.literal("runtime-open-failed")]),
  'workspace': z.string(),
  'detail': z.string(),
  'detectedAt': z.string(),
})]),
  'counts': z.object({
  'total': z.number(),
  'notStarted': z.number(),
  'pending': z.number(),
  'running': z.number(),
  'awaiting': z.number(),
  'completed': z.number(),
  'failed': z.number(),
  'timedOut': z.number(),
  'canceled': z.number(),
}),
  'startedAt': z.string(),
  'finishedAt': z.string().optional(),
  'tree': z.array(z.object({
  'activityId': z.string(),
  'label': z.string(),
  'kind': z.string(),
  'status': z.union([z.literal("pending"), z.literal("running"), z.literal("awaiting"), z.literal("completed"), z.literal("failed"), z.literal("not_started"), z.literal("not_selected"), z.literal("starting"), z.literal("ready"), z.literal("timed_out"), z.literal("cancelled"), z.literal("mixed")]),
  'startedAt': z.string().optional(),
  'durationMs': z.number().optional(),
  'progress': z.object({
  'completed': z.number(),
  'total': z.number(),
}).optional(),
  'agent': z.object({
  'name': z.string().optional(),
  'phase': z.union([z.literal("starting"), z.literal("responding"), z.literal("reported-thought"), z.literal("planning"), z.literal("tool"), z.literal("output-repair"), z.literal("settling"), z.literal("settled")]).optional(),
  'turn': z.number().optional(),
  'tool': z.object({
  'name': z.string(),
  'title': z.string().optional(),
  'state': z.union([z.literal("running"), z.literal("completed"), z.literal("failed"), z.literal("canceled")]),
}).optional(),
  'telemetry': z.object({
  'inputTokens': z.number().optional(),
  'outputTokens': z.number().optional(),
  'totalTokens': z.number().optional(),
  'contextWindow': z.object({
  'used': z.number(),
  'size': z.number(),
}).optional(),
}).optional(),
}).optional(),
  'children': z.array(z.lazy(() => ActivityNodeRemoteCodec$schema2)),
})),
}).optional(),
}),
})])
const _acpus_dsh_acpus_readActivityDetail_parameter_0$schema = z.object({
  'sessionId': z.string(),
  'generation': z.number(),
  'activityId': z.string(),
})
const _acpus_dsh_acpus_readActivityDetail_result$schema = z.union([z.object({
  'status': z.literal("available"),
  'detail': z.union([z.object({
  'kind': z.literal("agent"),
  'agent': z.string(),
  'model': z.string().optional(),
  'prompt': z.intersection(z.object({
  'text': z.string(),
  'truncated': z.boolean(),
}), z.object({
  'origin': z.union([z.literal("authored"), z.literal("steering"), z.literal("repair")]),
})).optional(),
  'result': z.union([z.object({
  'kind': z.literal("output"),
  'format': z.union([z.literal("text"), z.literal("json")]),
  'text': z.string(),
  'truncated': z.boolean(),
}), z.object({
  'kind': z.literal("completed-without-output"),
}), z.object({
  'kind': z.union([z.literal("failed"), z.literal("timed-out")]),
  'code': z.string().optional(),
  'message': z.string(),
}), z.object({
  'kind': z.literal("canceled"),
})]).optional(),
}), z.object({
  'kind': z.literal("task"),
  'input': z.intersection(z.object({
  'text': z.string(),
  'truncated': z.boolean(),
}), z.object({
  'format': z.union([z.literal("text"), z.literal("json")]),
})),
  'result': z.union([z.object({
  'kind': z.literal("output"),
  'format': z.union([z.literal("text"), z.literal("json")]),
  'text': z.string(),
  'truncated': z.boolean(),
}), z.object({
  'kind': z.literal("completed-without-output"),
}), z.object({
  'kind': z.union([z.literal("failed"), z.literal("timed-out")]),
  'code': z.string().optional(),
  'message': z.string(),
}), z.object({
  'kind': z.literal("canceled"),
})]).optional(),
})]),
}), z.object({
  'status': z.literal("rejected"),
  'reason': z.union([z.literal("task-unavailable"), z.literal("node-unavailable"), z.literal("detail-unavailable"), z.literal("temporarily-unavailable")]),
})])
const _acpus_dsh_acpus_readAgentPresets_parameter_0$schema = z.object({})
const _acpus_dsh_acpus_readAgentPresets_result$schema = z.object({
  'presets': z.array(z.object({
  'id': z.string(),
  'guidance': z.string(),
  'scope': z.union([z.literal("host"), z.literal("project"), z.literal("global")]),
})),
})
const _acpus_dsh_acpus_readSessionActivity_parameter_0$schema = z.object({
  'sessionId': z.string(),
  'task': z.object({
  'name': z.string(),
  'occurrence': z.number(),
}).optional(),
})
const _acpus_dsh_acpus_readSessionActivity_result$schema = z.object({
  'sessionId': z.string(),
  'revision': z.number(),
  'tasks': z.array(z.object({
  'task': z.object({
  'name': z.string(),
  'occurrence': z.number(),
}),
  'status': z.union([z.literal("pending"), z.literal("running"), z.literal("awaiting"), z.literal("paused"), z.literal("completed"), z.literal("failed"), z.literal("canceled")]),
  'availability': z.union([z.object({
  'status': z.literal("available"),
}), z.object({
  'status': z.literal("unavailable"),
  'reason': z.union([z.literal("workspace-unavailable"), z.literal("runtime-authority-busy"), z.literal("runtime-store-unavailable"), z.literal("runtime-store-unsupported"), z.literal("runtime-configuration-invalid"), z.literal("runtime-open-failed")]),
  'workspace': z.string(),
  'detail': z.string(),
  'detectedAt': z.string(),
})]),
  'counts': z.object({
  'total': z.number(),
  'notStarted': z.number(),
  'pending': z.number(),
  'running': z.number(),
  'awaiting': z.number(),
  'completed': z.number(),
  'failed': z.number(),
  'timedOut': z.number(),
  'canceled': z.number(),
}),
  'startedAt': z.string(),
  'finishedAt': z.string().optional(),
  'forkedFrom': z.object({
  'name': z.string(),
  'occurrence': z.number(),
}).optional(),
})),
  'tasksTruncated': z.boolean(),
  'task': z.object({
  'selector': z.object({
  'name': z.string(),
  'occurrence': z.number(),
}),
  'generation': z.number(),
  'status': z.union([z.literal("pending"), z.literal("running"), z.literal("awaiting"), z.literal("paused"), z.literal("completed"), z.literal("failed"), z.literal("canceled")]),
  'availability': z.union([z.object({
  'status': z.literal("available"),
}), z.object({
  'status': z.literal("unavailable"),
  'reason': z.union([z.literal("workspace-unavailable"), z.literal("runtime-authority-busy"), z.literal("runtime-store-unavailable"), z.literal("runtime-store-unsupported"), z.literal("runtime-configuration-invalid"), z.literal("runtime-open-failed")]),
  'workspace': z.string(),
  'detail': z.string(),
  'detectedAt': z.string(),
})]),
  'counts': z.object({
  'total': z.number(),
  'notStarted': z.number(),
  'pending': z.number(),
  'running': z.number(),
  'awaiting': z.number(),
  'completed': z.number(),
  'failed': z.number(),
  'timedOut': z.number(),
  'canceled': z.number(),
}),
  'startedAt': z.string(),
  'finishedAt': z.string().optional(),
  'tree': z.array(z.object({
  'activityId': z.string(),
  'label': z.string(),
  'kind': z.string(),
  'status': z.union([z.literal("pending"), z.literal("running"), z.literal("awaiting"), z.literal("completed"), z.literal("failed"), z.literal("not_started"), z.literal("not_selected"), z.literal("starting"), z.literal("ready"), z.literal("timed_out"), z.literal("cancelled"), z.literal("mixed")]),
  'startedAt': z.string().optional(),
  'durationMs': z.number().optional(),
  'progress': z.object({
  'completed': z.number(),
  'total': z.number(),
}).optional(),
  'agent': z.object({
  'name': z.string().optional(),
  'phase': z.union([z.literal("starting"), z.literal("responding"), z.literal("reported-thought"), z.literal("planning"), z.literal("tool"), z.literal("output-repair"), z.literal("settling"), z.literal("settled")]).optional(),
  'turn': z.number().optional(),
  'tool': z.object({
  'name': z.string(),
  'title': z.string().optional(),
  'state': z.union([z.literal("running"), z.literal("completed"), z.literal("failed"), z.literal("canceled")]),
}).optional(),
  'telemetry': z.object({
  'inputTokens': z.number().optional(),
  'outputTokens': z.number().optional(),
  'totalTokens': z.number().optional(),
  'contextWindow': z.object({
  'used': z.number(),
  'size': z.number(),
}).optional(),
}).optional(),
}).optional(),
  'children': z.array(z.lazy(() => ActivityNodeRemoteCodec$schema)),
})),
}).optional(),
})

export const TYPERT_REMOTE = {
  package: '@acpus/dsh',
  descriptors: [
    {
      id: '@acpus/dsh#acpus/awaitSessionActivityRevision',
      service: 'acpusMode',
      namespace: 'acpus',
      method: 'awaitSessionActivityRevision',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'input',
          wire: 'input',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@acpus/dsh/projection#AwaitSessionActivityRevisionRequest',
            schema: _acpus_dsh_acpus_awaitSessionActivityRevision_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@acpus/dsh/projection#AwaitSessionActivityRevisionResult',
        schema: _acpus_dsh_acpus_awaitSessionActivityRevision_result$schema,
      },
      sourceLocation: {"file":"packages/dsh/src/host/mode.ts","line":446,"column":3},
    },
    {
      id: '@acpus/dsh#acpus/cancelSessionTask',
      service: 'acpusMode',
      namespace: 'acpus',
      method: 'cancelSessionTask',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'input',
          wire: 'input',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@acpus/dsh/projection#CancelSessionTaskRequest',
            schema: _acpus_dsh_acpus_cancelSessionTask_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@acpus/dsh/projection#CancelSessionTaskResult',
        schema: _acpus_dsh_acpus_cancelSessionTask_result$schema,
      },
      sourceLocation: {"file":"packages/dsh/src/host/mode.ts","line":458,"column":9},
    },
    {
      id: '@acpus/dsh#acpus/readActivityDetail',
      service: 'acpusMode',
      namespace: 'acpus',
      method: 'readActivityDetail',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'input',
          wire: 'input',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@acpus/dsh/projection#ReadActivityDetailRequest',
            schema: _acpus_dsh_acpus_readActivityDetail_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@acpus/dsh/projection#ReadActivityDetailResult',
        schema: _acpus_dsh_acpus_readActivityDetail_result$schema,
      },
      sourceLocation: {"file":"packages/dsh/src/host/mode.ts","line":394,"column":9},
    },
    {
      id: '@acpus/dsh#acpus/readAgentPresets',
      service: 'acpusMode',
      namespace: 'acpus',
      method: 'readAgentPresets',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: '_input',
          wire: '_input',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@acpus/dsh/projection#ReadAgentPresetsRequest',
            schema: _acpus_dsh_acpus_readAgentPresets_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@acpus/dsh/projection#ReadAgentPresetsResult',
        schema: _acpus_dsh_acpus_readAgentPresets_result$schema,
      },
      sourceLocation: {"file":"packages/dsh/src/host/mode.ts","line":380,"column":9},
    },
    {
      id: '@acpus/dsh#acpus/readSessionActivity',
      service: 'acpusMode',
      namespace: 'acpus',
      method: 'readSessionActivity',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'input',
          wire: 'input',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@acpus/dsh/projection#ReadSessionActivityRequest',
            schema: _acpus_dsh_acpus_readSessionActivity_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@acpus/dsh/projection#SessionActivityProjection',
        schema: _acpus_dsh_acpus_readSessionActivity_result$schema,
      },
      sourceLocation: {"file":"packages/dsh/src/host/mode.ts","line":387,"column":3},
    },
  ],
}

export default TYPERT_REMOTE
