/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const ActivityNodeRemoteCodec$schema = z.object({
  'activityId': z.string(),
  'label': z.string(),
  'kind': z.string(),
  'status': z.union([z.literal("pending"), z.literal("running"), z.literal("awaiting"), z.literal("completed"), z.literal("failed"), z.literal("not_started"), z.literal("not_selected"), z.literal("starting"), z.literal("ready"), z.literal("timed_out"), z.literal("cancelled"), z.literal("mixed")]),
  'startedAt': z.string().optional(),
  'durationMs': z.number().optional(),
  'progress': z.object({
  'completed': z.number(),
  'total': z.number(),
}).optional(),
  'agent': z.object({
  'name': z.string().optional(),
  'phase': z.union([z.literal("starting"), z.literal("responding"), z.literal("reported-thought"), z.literal("planning"), z.literal("tool"), z.literal("output-repair"), z.literal("settling"), z.literal("settled")]).optional(),
  'turn': z.number().optional(),
  'tool': z.object({
  'name': z.string(),
  'title': z.string().optional(),
  'state': z.union([z.literal("running"), z.literal("completed"), z.literal("failed"), z.literal("canceled")]),
}).optional(),
  'telemetry': z.object({
  'inputTokens': z.number().optional(),
  'outputTokens': z.number().optional(),
  'totalTokens': z.number().optional(),
  'contextWindow': z.object({
  'used': z.number(),
  'size': z.number(),
}).optional(),
}).optional(),
}).optional(),
  'children': z.array(z.lazy(() => ActivityNodeRemoteCodec$schema)),
})
const ActivityNodeRemoteCodec$schema2 = z.object({
  'activityId': z.string(),
  'label': z.string(),
  'kind': z.string(),
  'status': z.union([z.literal("pending"), z.literal("running"), z.literal("awaiting"), z.literal("completed"), z.literal("failed"), z.literal("not_started"), z.literal("not_selected"), z.literal("starting"), z.literal("ready"), z.literal("timed_out"), z.literal("cancelled"), z.literal("mixed")]),
  'startedAt': z.string().optional(),
  'durationMs': z.number().optional(),
  'progress': z.object({
  'completed': z.number(),
  'total': z.number(),
}).optional(),
  'agent': z.object({
  'name': z.string().optional(),
  'phase': z.union([z.literal("starting"), z.literal("responding"), z.literal("reported-thought"), z.literal("planning"), z.literal("tool"), z.literal("output-repair"), z.literal("settling"), z.literal("settled")]).optional(),
  'turn': z.number().optional(),
  'tool': z.object({
  'name': z.string(),
  'title': z.string().optional(),
  'state': z.union([z.literal("running"), z.literal("completed"), z.literal("failed"), z.literal("canceled")]),
}).optional(),
  'telemetry': z.object({
  'inputTokens': z.number().optional(),
  'outputTokens': z.number().optional(),
  'totalTokens': z.number().optional(),
  'contextWindow': z.object({
  'used': z.number(),
  'size': z.number(),
}).optional(),
}).optional(),
}).optional(),
  'children': z.array(z.lazy(() => ActivityNodeRemoteCodec$schema2)),
})
const _acpus_dsh_acpus_awaitSessionActivityRevision_parameter_0$schema = z.object({
  'sessionId': z.string(),
  'afterRevision': z.number(),
})
const _acpus_dsh_acpus_awaitSessionActivityRevision_result$schema = z.object({
  'revision': z.number(),
})
const _acpus_dsh_acpus_cancelSessionTask_parameter_0$schema = z.object({
  'sessionId': z.string(),
  'generation': z.number(),
})
const _acpus_dsh_acpus_cancelSessionTask_result$schema = z.union([z.object({
  'status': z.literal("applied"),
  'projection': z.object({
  'sessionId': z.string(),
  'revision': z.number(),
  'tasks': z.array(z.object({
  'task': z.object({
  'name': z.string(),
  'occurrence': z.number(),
}),
  'status': z.union([z.literal("pending"), z.literal("running"), z.literal("awaiting"), z.literal("paused"), z.literal("completed"), z.literal("failed"), z.literal("canceled")]),
  'availability': z.union([z.object({
  'status': z.literal("available"),
}), z.object({
  'status': z.literal("unavailable"),
  'reason': z.union([z.literal("workspace-unavailable"), z.literal("runtime-authority-busy"), z.literal("runtime-store-unavailable"), z.literal("runtime-store-unsupported"), z.literal("runtime-configuration-invalid"), z.literal("runtime-open-failed")]),
  'workspace': z.string(),
  'detail': z.string(),
  'detectedAt': z.string(),
})]),
  'counts': z.object({
  'total': z.number(),
  'notStarted': z.number(),
  'pending': z.number(),
  'running': z.number(),
  'awaiting': z.number(),
  'completed': z.number(),
  'failed': z.number(),
  'timedOut': z.number(),
  'canceled': z.number(),
}),
  'startedAt': z.string(),
  'finishedAt': z.string().optional(),
  'forkedFrom': z.object({
  'name': z.string(),
  'occurrence': z.number(),
}).optional(),
})),
  'tasksTruncated': z.boolean(),
  'task': z.object({
  'selector': z.object({
  'name': z.string(),
  'occurrence': z.number(),
}),
  'generation': z.number(),
  'status': z.union([z.literal("pending"), z.literal("running"), z.literal("awaiting"), z.literal("paused"), z.literal("completed"), z.literal("failed"), z.literal("canceled")]),
  'availability': z.union([z.object({
  'status': z.literal("available"),
}), z.object({
  'status': z.literal("unavailable"),
  'reason': z.union([z.literal("workspace-unavailable"), z.literal("runtime-authority-busy"), z.literal("runtime-store-unavailable"), z.literal("runtime-store-unsupported"), z.literal("runtime-configuration-invalid"), z.literal("runtime-open-failed")]),
  'workspace': z.string(),
  'detail': z.string(),
  'detectedAt': z.string(),
})]),
  'counts': z.object({
  'total': z.number(),
  'notStarted': z.number(),
  'pending': z.number(),
  'running': z.number(),
  'awaiting': z.number(),
  'completed': z.number(),
  'failed': z.number(),
  'timedOut': z.number(),
  'canceled': z.number(),
}),
  'startedAt': z.string(),
  'finishedAt': z.string().optional(),
  'tree': z.array(z.object({
  'activityId': z.string(),
  'label': z.string(),
  'kind': z.string(),
  'status': z.union([z.literal("pending"), z.literal("running"), z.literal("awaiting"), z.literal("completed"), z.literal("failed"), z.literal("not_started"), z.literal("not_selected"), z.literal("starting"), z.literal("ready"), z.literal("timed_out"), z.literal("cancelled"), z.literal("mixed")]),
  'startedAt': z.string().optional(),
  'durationMs': z.number().optional(),
  'progress': z.object({
  'completed': z.number(),
  'total': z.number(),
}).optional(),
  'agent': z.object({
  'name': z.string().optional(),
  'phase': z.union([z.literal("starting"), z.literal("responding"), z.literal("reported-thought"), z.literal("planning"), z.literal("tool"), z.literal("output-repair"), z.literal("settling"), z.literal("settled")]).optional(),
  'turn': z.number().optional(),
  'tool': z.object({
  'name': z.string(),
  'title': z.string().optional(),
  'state': z.union([z.literal("running"), z.literal("completed"), z.literal("failed"), z.literal("canceled")]),
}).optional(),
  'telemetry': z.object({
  'inputTokens': z.number().optional(),
  'outputTokens': z.number().optional(),
  'totalTokens': z.number().optional(),
  'contextWindow': z.object({
  'used': z.number(),
  'size': z.number(),
}).optional(),
}).optional(),
}).optional(),
  'children': z.array(z.lazy(() => ActivityNodeRemoteCodec$schema2)),
})),
}).optional(),
}),
}), z.object({
  'status': z.literal("rejected"),
  'reason': z.union([z.literal("task-unavailable"), z.literal("temporarily-unavailable"), z.literal("already-terminal"), z.literal("not-controllable")]),
  'projection': z.object({
  'sessionId': z.string(),
  'revision': z.number(),
  'tasks': z.array(z.object({
  'task': z.object({
  'name': z.string(),
  'occurrence': z.number(),
}),
  'status': z.union([z.literal("pending"), z.literal("running"), z.literal("awaiting"), z.literal("paused"), z.literal("completed"), z.literal("failed"), z.literal("canceled")]),
  'availability': z.union([z.object({
  'status': z.literal("available"),
}), z.object({
  'status': z.literal("unavailable"),
  'reason': z.union([z.literal("workspace-unavailable"), z.literal("runtime-authority-busy"), z.literal("runtime-store-unavailable"), z.literal("runtime-store-unsupported"), z.literal("runtime-configuration-invalid"), z.literal("runtime-open-failed")]),
  'workspace': z.string(),
  'detail': z.string(),
  'detectedAt': z.string(),
})]),
  'counts': z.object({
  'total': z.number(),
  'notStarted': z.number(),
  'pending': z.number(),
  'running': z.number(),
  'awaiting': z.number(),
  'completed': z.number(),
  'failed': z.number(),
  'timedOut': z.number(),
  'canceled': z.number(),
}),
  'startedAt': z.string(),
  'finishedAt': z.string().optional(),
  'forkedFrom': z.object({
  'name': z.string(),
  'occurrence': z.number(),
}).optional(),
})),
  'tasksTruncated': z.boolean(),
  'task': z.object({
  'selector': z.object({
  'name': z.string(),
  'occurrence': z.number(),
}),
  'generation': z.number(),
  'status': z.union([z.literal("pending"), z.literal("running"), z.literal("awaiting"), z.literal("paused"), z.literal("completed"), z.literal("failed"), z.literal("canceled")]),
  'availability': z.union([z.object({
  'status': z.literal("available"),
}), z.object({
  'status': z.literal("unavailable"),
  'reason': z.union([z.literal("workspace-unavailable"), z.literal("runtime-authority-busy"), z.literal("runtime-store-unavailable"), z.literal("runtime-store-unsupported"), z.literal("runtime-configuration-invalid"), z.literal("runtime-open-failed")]),
  'workspace': z.string(),
  'detail': z.string(),
  'detectedAt': z.string(),
})]),
  'counts': z.object({
  'total': z.number(),
  'notStarted': z.number(),
  'pending': z.number(),
  'running': z.number(),
  'awaiting': z.number(),
  'completed': z.number(),
  'failed': z.number(),
  'timedOut': z.number(),
  'canceled': z.number(),
}),
  'startedAt': z.string(),
  'finishedAt': z.string().optional(),
  'tree': z.array(z.object({
  'activityId': z.string(),
  'label': z.string(),
  'kind': z.string(),
  'status': z.union([z.literal("pending"), z.literal("running"), z.literal("awaiting"), z.literal("completed"), z.literal("failed"), z.literal("not_started"), z.literal("not_selected"), z.literal("starting"), z.literal("ready"), z.literal("timed_out"), z.literal("cancelled"), z.literal("mixed")]),
  'startedAt': z.string().optional(),
  'durationMs': z.number().optional(),
  'progress': z.object({
  'completed': z.number(),
  'total': z.number(),
}).optional(),
  'agent': z.object({
  'name': z.string().optional(),
  'phase': z.union([z.literal("starting"), z.literal("responding"), z.literal("reported-thought"), z.literal("planning"), z.literal("tool"), z.literal("output-repair"), z.literal("settling"), z.literal("settled")]).optional(),
  'turn': z.number().optional(),
  'tool': z.object({
  'name': z.string(),
  'title': z.string().optional(),
  'state': z.union([z.literal("running"), z.literal("completed"), z.literal("failed"), z.literal("canceled")]),
}).optional(),
  'telemetry': z.object({
  'inputTokens': z.number().optional(),
  'outputTokens': z.number().optional(),
  'totalTokens': z.number().optional(),
  'contextWindow': z.object({
  'used': z.number(),
  'size': z.number(),
}).optional(),
}).optional(),
}).optional(),
  'children': z.array(z.lazy(() => ActivityNodeRemoteCodec$schema2)),
})),
}).optional(),
}),
})])
const _acpus_dsh_acpus_readActivityDetail_parameter_0$schema = z.object({
  'sessionId': z.string(),
  'generation': z.number(),
  'activityId': z.string(),
})
const _acpus_dsh_acpus_readActivityDetail_result$schema = z.union([z.object({
  'status': z.literal("available"),
  'detail': z.union([z.object({
  'kind': z.literal("agent"),
  'agent': z.string(),
  'model': z.string().optional(),
  'prompt': z.intersection(z.object({
  'text': z.string(),
  'truncated': z.boolean(),
}), z.object({
  'origin': z.union([z.literal("authored"), z.literal("steering"), z.literal("repair")]),
})).optional(),
  'result': z.union([z.object({
  'kind': z.literal("output"),
  'format': z.union([z.literal("text"), z.literal("json")]),
  'text': z.string(),
  'truncated': z.boolean(),
}), z.object({
  'kind': z.literal("completed-without-output"),
}), z.object({
  'kind': z.union([z.literal("failed"), z.literal("timed-out")]),
  'code': z.string().optional(),
  'message': z.string(),
}), z.object({
  'kind': z.literal("canceled"),
})]).optional(),
}), z.object({
  'kind': z.literal("task"),
  'input': z.intersection(z.object({
  'text': z.string(),
  'truncated': z.boolean(),
}), z.object({
  'format': z.union([z.literal("text"), z.literal("json")]),
})),
  'result': z.union([z.object({
  'kind': z.literal("output"),
  'format': z.union([z.literal("text"), z.literal("json")]),
  'text': z.string(),
  'truncated': z.boolean(),
}), z.object({
  'kind': z.literal("completed-without-output"),
}), z.object({
  'kind': z.union([z.literal("failed"), z.literal("timed-out")]),
  'code': z.string().optional(),
  'message': z.string(),
}), z.object({
  'kind': z.literal("canceled"),
})]).optional(),
})]),
}), z.object({
  'status': z.literal("rejected"),
  'reason': z.union([z.literal("task-unavailable"), z.literal("node-unavailable"), z.literal("detail-unavailable"), z.literal("temporarily-unavailable")]),
})])
const _acpus_dsh_acpus_readAgentPresets_parameter_0$schema = z.object({})
const _acpus_dsh_acpus_readAgentPresets_result$schema = z.object({
  'presets': z.array(z.object({
  'id': z.string(),
  'guidance': z.string(),
  'scope': z.union([z.literal("host"), z.literal("project"), z.literal("global")]),
  'agent': z.union([z.object({
  'use': z.string(),
  'model': z.string().optional(),
  'config': z.array(z.object({
  'key': z.string(),
  'value': z.string(),
})).optional(),
}), z.object({
  'command': z.string(),
  'model': z.string().optional(),
  'config': z.array(z.object({
  'key': z.string(),
  'value': z.string(),
})).optional(),
})]),
})),
})
const _acpus_dsh_acpus_readSessionActivity_parameter_0$schema = z.object({
  'sessionId': z.string(),
  'task': z.object({
  'name': z.string(),
  'occurrence': z.number(),
}).optional(),
})
const _acpus_dsh_acpus_readSessionActivity_result$schema = z.object({
  'sessionId': z.string(),
  'revision': z.number(),
  'tasks': z.array(z.object({
  'task': z.object({
  'name': z.string(),
  'occurrence': z.number(),
}),
  'status': z.union([z.literal("pending"), z.literal("running"), z.literal("awaiting"), z.literal("paused"), z.literal("completed"), z.literal("failed"), z.literal("canceled")]),
  'availability': z.union([z.object({
  'status': z.literal("available"),
}), z.object({
  'status': z.literal("unavailable"),
  'reason': z.union([z.literal("workspace-unavailable"), z.literal("runtime-authority-busy"), z.literal("runtime-store-unavailable"), z.literal("runtime-store-unsupported"), z.literal("runtime-configuration-invalid"), z.literal("runtime-open-failed")]),
  'workspace': z.string(),
  'detail': z.string(),
  'detectedAt': z.string(),
})]),
  'counts': z.object({
  'total': z.number(),
  'notStarted': z.number(),
  'pending': z.number(),
  'running': z.number(),
  'awaiting': z.number(),
  'completed': z.number(),
  'failed': z.number(),
  'timedOut': z.number(),
  'canceled': z.number(),
}),
  'startedAt': z.string(),
  'finishedAt': z.string().optional(),
  'forkedFrom': z.object({
  'name': z.string(),
  'occurrence': z.number(),
}).optional(),
})),
  'tasksTruncated': z.boolean(),
  'task': z.object({
  'selector': z.object({
  'name': z.string(),
  'occurrence': z.number(),
}),
  'generation': z.number(),
  'status': z.union([z.literal("pending"), z.literal("running"), z.literal("awaiting"), z.literal("paused"), z.literal("completed"), z.literal("failed"), z.literal("canceled")]),
  'availability': z.union([z.object({
  'status': z.literal("available"),
}), z.object({
  'status': z.literal("unavailable"),
  'reason': z.union([z.literal("workspace-unavailable"), z.literal("runtime-authority-busy"), z.literal("runtime-store-unavailable"), z.literal("runtime-store-unsupported"), z.literal("runtime-configuration-invalid"), z.literal("runtime-open-failed")]),
  'workspace': z.string(),
  'detail': z.string(),
  'detectedAt': z.string(),
})]),
  'counts': z.object({
  'total': z.number(),
  'notStarted': z.number(),
  'pending': z.number(),
  'running': z.number(),
  'awaiting': z.number(),
  'completed': z.number(),
  'failed': z.number(),
  'timedOut': z.number(),
  'canceled': z.number(),
}),
  'startedAt': z.string(),
  'finishedAt': z.string().optional(),
  'tree': z.array(z.object({
  'activityId': z.string(),
  'label': z.string(),
  'kind': z.string(),
  'status': z.union([z.literal("pending"), z.literal("running"), z.literal("awaiting"), z.literal("completed"), z.literal("failed"), z.literal("not_started"), z.literal("not_selected"), z.literal("starting"), z.literal("ready"), z.literal("timed_out"), z.literal("cancelled"), z.literal("mixed")]),
  'startedAt': z.string().optional(),
  'durationMs': z.number().optional(),
  'progress': z.object({
  'completed': z.number(),
  'total': z.number(),
}).optional(),
  'agent': z.object({
  'name': z.string().optional(),
  'phase': z.union([z.literal("starting"), z.literal("responding"), z.literal("reported-thought"), z.literal("planning"), z.literal("tool"), z.literal("output-repair"), z.literal("settling"), z.literal("settled")]).optional(),
  'turn': z.number().optional(),
  'tool': z.object({
  'name': z.string(),
  'title': z.string().optional(),
  'state': z.union([z.literal("running"), z.literal("completed"), z.literal("failed"), z.literal("canceled")]),
}).optional(),
  'telemetry': z.object({
  'inputTokens': z.number().optional(),
  'outputTokens': z.number().optional(),
  'totalTokens': z.number().optional(),
  'contextWindow': z.object({
  'used': z.number(),
  'size': z.number(),
}).optional(),
}).optional(),
}).optional(),
  'children': z.array(z.lazy(() => ActivityNodeRemoteCodec$schema)),
})),
}).optional(),
})

export const TYPERT = {
  package: '@acpus/dsh',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@acpus/dsh#acpus/awaitSessionActivityRevision',
      service: 'acpusMode',
      namespace: 'acpus',
      method: 'awaitSessionActivityRevision',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'input',
          wire: 'input',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@acpus/dsh/projection#AwaitSessionActivityRevisionRequest',
            schema: _acpus_dsh_acpus_awaitSessionActivityRevision_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@acpus/dsh/projection#AwaitSessionActivityRevisionResult',
        schema: _acpus_dsh_acpus_awaitSessionActivityRevision_result$schema,
      },
      sourceLocation: {"file":"packages/dsh/src/host/mode.ts","line":501,"column":3},
    },
    {
      id: '@acpus/dsh#acpus/cancelSessionTask',
      service: 'acpusMode',
      namespace: 'acpus',
      method: 'cancelSessionTask',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'input',
          wire: 'input',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@acpus/dsh/projection#CancelSessionTaskRequest',
            schema: _acpus_dsh_acpus_cancelSessionTask_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@acpus/dsh/projection#CancelSessionTaskResult',
        schema: _acpus_dsh_acpus_cancelSessionTask_result$schema,
      },
      sourceLocation: {"file":"packages/dsh/src/host/mode.ts","line":512,"column":3},
    },
    {
      id: '@acpus/dsh#acpus/readActivityDetail',
      service: 'acpusMode',
      namespace: 'acpus',
      method: 'readActivityDetail',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'input',
          wire: 'input',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@acpus/dsh/projection#ReadActivityDetailRequest',
            schema: _acpus_dsh_acpus_readActivityDetail_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@acpus/dsh/projection#ReadActivityDetailResult',
        schema: _acpus_dsh_acpus_readActivityDetail_result$schema,
      },
      sourceLocation: {"file":"packages/dsh/src/host/mode.ts","line":453,"column":9},
    },
    {
      id: '@acpus/dsh#acpus/readAgentPresets',
      service: 'acpusMode',
      namespace: 'acpus',
      method: 'readAgentPresets',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: '_input',
          wire: '_input',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@acpus/dsh/projection#ReadAgentPresetsRequest',
            schema: _acpus_dsh_acpus_readAgentPresets_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@acpus/dsh/projection#ReadAgentPresetsResult',
        schema: _acpus_dsh_acpus_readAgentPresets_result$schema,
      },
      sourceLocation: {"file":"packages/dsh/src/host/mode.ts","line":438,"column":9},
    },
    {
      id: '@acpus/dsh#acpus/readSessionActivity',
      service: 'acpusMode',
      namespace: 'acpus',
      method: 'readSessionActivity',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'input',
          wire: 'input',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@acpus/dsh/projection#ReadSessionActivityRequest',
            schema: _acpus_dsh_acpus_readSessionActivity_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@acpus/dsh/projection#SessionActivityProjection',
        schema: _acpus_dsh_acpus_readSessionActivity_result$schema,
      },
      sourceLocation: {"file":"packages/dsh/src/host/mode.ts","line":446,"column":3},
    },
  ],
  model: {
    "services": [
      {
        "tags": [],
        "key": "acpusMode",
        "exportName": "AcpusMode",
        "members": [
          {
            "kind": "method",
            "name": "run",
            "signature": "run(request: AcpusRunRequest): Promise<AcpusRunReceipt | InvalidWorkflow>"
          },
          {
            "kind": "method",
            "name": "runtime",
            "signature": "runtime(workspace: string): Promise<WorkspaceRuntime>"
          },
          {
            "kind": "method",
            "name": "trustedAgentPresetChoices",
            "signature": "async trustedAgentPresetChoices(): Promise<readonly AgentPresetChoice[]>"
          },
          {
            "kind": "method",
            "name": "agentPresetChoices",
            "signature": "agentPresetChoices(workspace: string): Promise<AgentPresetSelectionView[]>"
          },
          {
            "kind": "method",
            "name": "applyAgentPresets",
            "signature": "async applyAgentPresets( input: ApplyAgentPresetsRequest, ): Promise<ApplyAgentPresetsResult>"
          },
          {
            "kind": "method",
            "name": "tasks",
            "signature": "tasks(sessionId: string, name?: string): Promise<AcpusTasksResult>"
          },
          {
            "kind": "method",
            "name": "resolveTask",
            "signature": "resolveTask( sessionId: string, selector?: DelegatedTaskSelector, ): Promise<{ runId: string; workspace: string; runtime: WorkspaceRuntime; generation: number; selector: ResolvedTaskSelector; link: AdmittedRunLink; }>"
          },
          {
            "kind": "method",
            "name": "reconcileTask",
            "signature": "reconcileTask(link: AdmittedRunLink): Promise<void>"
          },
          {
            "kind": "method",
            "name": "linkFork",
            "signature": "linkFork( sessionId: string, toolCallId: string, sourceGeneration: number, workspace: string, run: { id: string; name: string }, ): Promise<ResolvedTaskSelector>"
          },
          {
            "kind": "method",
            "name": "readAgentPresets",
            "signature": "@Remote async readAgentPresets( _input: ReadAgentPresetsRequest, ): Promise<ReadAgentPresetsResult>"
          },
          {
            "kind": "method",
            "name": "readSessionActivity",
            "signature": "@Remote readSessionActivity( input: ReadSessionActivityRequest, ): Promise<SessionActivityProjection>"
          },
          {
            "kind": "method",
            "name": "readActivityDetail",
            "signature": "@Remote async readActivityDetail( input: ReadActivityDetailRequest, ): Promise<ReadActivityDetailResult>"
          },
          {
            "kind": "method",
            "name": "awaitSessionActivityRevision",
            "signature": "@Remote awaitSessionActivityRevision( input: AwaitSessionActivityRevisionRequest, signal: AbortSignal, ): Promise<AwaitSessionActivityRevisionResult>"
          },
          {
            "kind": "method",
            "name": "cancelSessionTask",
            "signature": "@Remote cancelSessionTask( input: CancelSessionTaskRequest, ): Promise<CancelSessionTaskResult>"
          },
          {
            "kind": "method",
            "name": "prepareModelCancel",
            "signature": "prepareModelCancel( sessionId: string, generation: number, requestId: string, ): Promise< | { status: \"ready\"; control: StoredControl; link: AdmittedRunLink } | { status: \"rejected\"; reason: \"task-unavailable\" | \"already-terminal\" } >"
          },
          {
            "kind": "method",
            "name": "settleModelCancel",
            "signature": "settleModelCancel( controlId: string, outcome: \"applied\" | \"rejected\", reason?: \"not-controllable\" | \"temporarily-unavailable\", ): Promise<void>"
          }
        ],
        "types": [
          {
            "name": "AcpusRunReceipt",
            "declaration": "export type AcpusRunReceipt = { status: \"admitted\"; runId: string; task: ResolvedTaskSelector; };"
          },
          {
            "name": "AcpusRunRequest",
            "declaration": "export type AcpusRunRequest = { workspace: string; sessionId: string; toolCallId: string; workflow: string; input?: JsonValue; agents?: JsonValue; signal?: AbortSignal; };"
          },
          {
            "name": "AcpusRunStatus",
            "declaration": "export type AcpusRunStatus = \"pending\" | \"running\" | \"awaiting\" | \"paused\" | \"completed\" | \"failed\" | \"canceled\";"
          },
          {
            "name": "AcpusTaskAvailability",
            "declaration": "export type AcpusTaskAvailability = { status: \"available\"; } | { status: \"unavailable\"; reason: \"workspace-unavailable\" | \"runtime-authority-busy\" | \"runtime-store-unavailable\" | \"runtime-store-unsupported\" | \"runtime-configuration-invalid\" | \"runtime-open-failed\"; workspace: string; detail: string; detectedAt: string; };"
          },
          {
            "name": "AcpusTasksResult",
            "declaration": "export type AcpusTasksResult = { tasks: DelegatedTaskSummary[]; truncated: boolean; };"
          },
          {
            "name": "ActivityHoverDetail",
            "declaration": "export type ActivityHoverDetail = { kind: \"agent\"; agent: string; model?: string; prompt?: BoundedHoverText & { origin: \"authored\" | \"steering\" | \"repair\"; }; result?: HoverResult; } | { kind: \"task\"; input: BoundedHoverText & { format: \"text\" | \"json\"; }; result?: HoverResult; };"
          },
          {
            "name": "ActivityNode",
            "declaration": "export type ActivityNode = { activityId: string; label: string; kind: string; status: ActivityNodeStatus; startedAt?: string; durationMs?: number; progress?: { completed: number; total: number; }; agent?: AgentActivity; children: ActivityNode[]; };"
          },
          {
            "name": "ActivityNodeStatus",
            "declaration": "export type ActivityNodeStatus = \"not_started\" | \"not_selected\" | \"pending\" | \"starting\" | \"ready\" | \"running\" | \"awaiting\" | \"completed\" | \"failed\" | \"timed_out\" | \"cancelled\" | \"mixed\";"
          },
          {
            "name": "AdmittedRunLink",
            "declaration": "export type AdmittedRunLink = RunLink & { runId: string; workflowName: string; occurrence: number; };"
          },
          {
            "name": "AgentActivity",
            "declaration": "export type AgentActivity = { name?: string; phase?: \"starting\" | \"responding\" | \"reported-thought\" | \"planning\" | \"tool\" | \"output-repair\" | \"settling\" | \"settled\"; turn?: number; tool?: { name: string; title?: string; state: \"running\" | \"completed\" | \"failed\" | \"canceled\"; }; telemetry?: { inputTokens?: number; outputTokens?: number; totalTokens?: number; contextWindow?: { used: number; size: number; }; }; };"
          },
          {
            "name": "AgentPresetAgentView",
            "declaration": "export type AgentPresetAgentView = { use: string; model?: string; config?: AgentPresetConfigEntryView[]; } | { command: string; model?: string; config?: AgentPresetConfigEntryView[]; };"
          },
          {
            "name": "AgentPresetConfigEntryView",
            "declaration": "export type AgentPresetConfigEntryView = { key: string; value: string; };"
          },
          {
            "name": "AgentPresetSelectionView",
            "declaration": "export type AgentPresetSelectionView = Pick<AgentPresetChoice, \"id\" | \"guidance\">;"
          },
          {
            "name": "AgentPresetView",
            "declaration": "export type AgentPresetView = { id: string; guidance: string; scope: \"host\" | \"project\" | \"global\"; agent: AgentPresetAgentView; };"
          },
          {
            "name": "ApplyAgentPresetsRequest",
            "declaration": "export type ApplyAgentPresetsRequest = { workspace: string; scope: WritableAgentPresetScope; changes: readonly AgentPresetChange[]; };"
          },
          {
            "name": "ApplyAgentPresetsResult",
            "declaration": "export type ApplyAgentPresetsResult = { status: \"applied\"; } | { status: \"rejected\"; reason: string; };"
          },
          {
            "name": "AwaitSessionActivityRevisionRequest",
            "declaration": "export type AwaitSessionActivityRevisionRequest = { sessionId: string; afterRevision: number; };"
          },
          {
            "name": "AwaitSessionActivityRevisionResult",
            "declaration": "export type AwaitSessionActivityRevisionResult = { revision: number; };"
          },
          {
            "name": "BoundedHoverText",
            "declaration": "export type BoundedHoverText = { text: string; truncated: boolean; };"
          },
          {
            "name": "CancelSessionTaskRequest",
            "declaration": "export type CancelSessionTaskRequest = { sessionId: string; generation: number; };"
          },
          {
            "name": "CancelSessionTaskResult",
            "declaration": "export type CancelSessionTaskResult = { status: \"applied\"; projection: SessionActivityProjection; } | { status: \"rejected\"; reason: \"task-unavailable\" | \"already-terminal\" | \"not-controllable\" | \"temporarily-unavailable\"; projection: SessionActivityProjection; };"
          },
          {
            "name": "ControlRejectionReason",
            "declaration": "export type ControlRejectionReason = \"already-terminal\" | \"not-controllable\" | \"temporarily-unavailable\";"
          },
          {
            "name": "DelegatedTaskActivity",
            "declaration": "export type DelegatedTaskActivity = { selector: ResolvedTaskSelector; generation: number; status: AcpusRunStatus; availability: AcpusTaskAvailability; counts: RunCounts; startedAt: string; finishedAt?: string; tree: ActivityNode[]; };"
          },
          {
            "name": "DelegatedTaskSelector",
            "declaration": "export type DelegatedTaskSelector = ResolvedTaskSelector;"
          },
          {
            "name": "DelegatedTaskSummary",
            "declaration": "export type DelegatedTaskSummary = { task: ResolvedTaskSelector; status: AcpusRunStatus; availability: AcpusTaskAvailability; counts: RunCounts; startedAt: string; finishedAt?: string; forkedFrom?: ResolvedTaskSelector; };"
          },
          {
            "name": "HoverResult",
            "declaration": "export type HoverResult = { kind: \"output\"; format: \"text\" | \"json\"; text: string; truncated: boolean; } | { kind: \"completed-without-output\"; } | { kind: \"failed\" | \"timed-out\"; code?: string; message: string; } | { kind: \"canceled\"; };"
          },
          {
            "name": "InspectionTreeEntry",
            "declaration": "export type InspectionTreeEntry = Extract<InspectionView, { kind: \"run\"; }>[\"tree\"][number];"
          },
          {
            "name": "InspectionVisibleState",
            "declaration": "export type InspectionVisibleState = Extract<InspectionTreeEntry, { type: \"item\"; }>[\"state\"];"
          },
          {
            "name": "InvalidWorkflow",
            "declaration": "export type InvalidWorkflow = { status: \"invalid\"; phase: string; diagnostics: WorkflowDiagnostic[]; };"
          },
          {
            "name": "ReadActivityDetailRequest",
            "declaration": "export type ReadActivityDetailRequest = { sessionId: string; generation: number; activityId: string; };"
          },
          {
            "name": "ReadActivityDetailResult",
            "declaration": "export type ReadActivityDetailResult = { status: \"available\"; detail: ActivityHoverDetail; } | { status: \"rejected\"; reason: \"task-unavailable\" | \"node-unavailable\" | \"detail-unavailable\" | \"temporarily-unavailable\"; };"
          },
          {
            "name": "ReadAgentPresetsRequest",
            "declaration": "export type ReadAgentPresetsRequest = {};"
          },
          {
            "name": "ReadAgentPresetsResult",
            "declaration": "export type ReadAgentPresetsResult = { presets: AgentPresetView[]; };"
          },
          {
            "name": "ReadSessionActivityRequest",
            "declaration": "export type ReadSessionActivityRequest = { sessionId: string; task?: ResolvedTaskSelector; };"
          },
          {
            "name": "ResolvedTaskSelector",
            "declaration": "export type ResolvedTaskSelector = { name: string; occurrence: number; };"
          },
          {
            "name": "RunCounts",
            "declaration": "export type RunCounts = { total: number; notStarted: number; pending: number; running: number; awaiting: number; completed: number; failed: number; timedOut: number; canceled: number; };"
          },
          {
            "name": "RunLink",
            "declaration": "export type RunLink = { workspace: string; admissionRequestId: string; runId?: string; workflowName?: string; occurrence?: number; forkedFromGeneration?: number; parentSessionId: string; generation: number; };"
          },
          {
            "name": "RuntimePoolOpenFailure",
            "declaration": "export type RuntimePoolOpenFailure = { type: \"workspace-unavailable\"; workspace: string; message: string; cause?: unknown; } | WorkspaceRuntimeOpenFailure;"
          },
          {
            "name": "SessionActivityProjection",
            "declaration": "export type SessionActivityProjection = { sessionId: string; revision: number; tasks: DelegatedTaskSummary[]; tasksTruncated: boolean; task?: DelegatedTaskActivity; };"
          },
          {
            "name": "StoredActivityNode",
            "declaration": "export type StoredActivityNode = { key: string; activityId: string; target?: string; label: string; kind: string; status: InspectionVisibleState[\"status\"]; startedAt?: string; durationMs?: number; progress?: { completed: number; total: number; }; agent?: { name?: string; phase?: NonNullable<Extract<InspectionTreeEntry, { type: \"item\"; }>[\"pulse\"]>[\"phase\"]; turn?: number; tool?: { name: string; title?: string; state: \"running\" | \"completed\" | \"failed\" | \"canceled\"; }; telemetry?: { inputTokens?: number; outputTokens?: number; totalTokens?: number; contextWindow?: { used: number; size: number; }; }; }; children: StoredActivityNode[]; };"
          },
          {
            "name": "StoredControl",
            "declaration": "export type StoredControl = { id: string; requestId: string; actor: \"user\" | \"model\"; parentSessionId: string; generation: number; workspace: string; runId: string; status: \"pending\" | \"applied\" | \"rejected\"; taskStatus?: StoredRunProjection[\"status\"]; reason?: ControlRejectionReason; };"
          },
          {
            "name": "StoredRunProjection",
            "declaration": "export type StoredRunProjection = { runId: string; workspace: string; admissionRequestId: string; generation: number; occurrence: number; forkedFromGeneration?: number; name: string; status: Extract<InspectionView, { kind: \"run\"; }>[\"run\"][\"status\"]; counts: InspectionCounts; createdAt: string; updatedAt: string; activity: StoredActivityNode[]; unavailable?: { reason: RuntimePoolOpenFailure[\"type\"]; detail: string; detectedAt: string; }; failure?: { origin: string; code?: string; message: string; }; actionRequirement?: StoredSignalRequirement; terminal?: { output?: { text: string; truncated: boolean; }; }; };"
          },
          {
            "name": "StoredSignalRequirement",
            "declaration": "export type StoredSignalRequirement = { selector: string; prompt?: string; expected?: string; };"
          },
          {
            "name": "WorkflowDiagnostic",
            "declaration": "export type WorkflowDiagnostic = { code: string; severity: \"error\" | \"info\" | \"warning\"; message: string; source?: { file?: string; line?: number; column?: number; }; path?: string; hint?: string; };"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
